name: Requirements archiver

on:
  schedule:
    # Run weekly on Sunday at 2 AM Pacific Time (9 AM UTC)
    - cron: "0 9 * * 0"
  workflow_dispatch: # Allow manual triggering
    inputs:
      force_release:
        description: "Force release creation even if no changes detected"
        required: false
        type: boolean
        default: false

permissions:
  contents: write

jobs:
  archive:
    runs-on: ubuntu-latest
    outputs:
      has-changes: ${{ steps.commit-changes.outputs.has-changes }}
      release-tag: ${{ steps.release-info.outputs.release-tag }}
      release-name: ${{ steps.release-info.outputs.release-name }}
      change-report: ${{ steps.release-info.outputs.change-report }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1 # Only fetch the latest commit to compare changes

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.11"
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Run archive process
        run: make archive-merit-badges archive-cub-adventures -j2

      - name: Build the index
        run: make index-merit-badges index-cub-adventures

      - name: Validate archives
        run: make validate-merit-badges validate-cub-adventures

      - name: Generate change reports
        run: make report-merit-badges report-cub-adventures

      - name: Upload change reports
        uses: actions/upload-artifact@v4
        with:
          name: change-reports
          path: |
            merit-badges-change-report.txt
            cub-adventures-change-report.txt
          retention-days: 7
          if-no-files-found: warn

      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: |
            run.log
            run-cub-adventures.log
          retention-days: 7
          if-no-files-found: warn

      - name: Upload merit badge markdown files as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: merit-badge-markdown
          path: |
            build/merit-badges/*.md
            build/merit-badges/images
          retention-days: 7
          if-no-files-found: warn

      - name: Upload cub adventures markdown files as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cub-adventure-markdown
          path: |
            build/cub-scout-adventures/*/*.md
            build/cub-scout-adventures/index.md
            build/cub-scout-adventures/*/images
          retention-days: 7
          if-no-files-found: warn

      - name: Upload merit badge JSON files as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: merit-badge-json
          path: |
            build/merit-badges/*.json
            build/merit-badges/images
          retention-days: 7
          if-no-files-found: warn

      - name: Upload cub adventure JSON files as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cub-adventure-json
          path: |
            build/cub-scout-adventures/*/*.json
            build/cub-scout-adventures/*/images
          retention-days: 7
          if-no-files-found: warn

      - name: Create job summary
        run: uv run src/scripts/format-change-summary.py $GITHUB_STEP_SUMMARY

      - name: Get release info
        id: release-info
        run: uv run src/scripts/generate-release-metadata.py $GITHUB_OUTPUT --merit-badge-report merit-badges-change-report.txt --cub-report cub-adventures-change-report.txt --run-number $GITHUB_RUN_NUMBER --run-attempt $GITHUB_RUN_ATTEMPT

      - name: Check for changes and commit
        id: commit-changes
        run: src/scripts/commit-changes.sh $GITHUB_OUTPUT "${{ steps.release-info.outputs.release-tag }}" "${{ steps.release-info.outputs.change-report }}"

      - name: Push changes
        if: steps.commit-changes.outputs.has-changes == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Check for failures
        if: failure()
        run: |
          echo "::error::Archiving job failed! This could indicate a change in the source website structure or validation failed."

  create-release:
    runs-on: ubuntu-latest
    needs: archive
    if: needs.archive.outputs.has-changes == 'true' || inputs.force_release == true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifacts for release
        uses: actions/download-artifact@v4
        with:
          path: release-assets

      - name: Validate artifacts and create archives
        run: src/scripts/create-release-archives.sh release-assets

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.archive.outputs.release-tag }}
          name: ${{ needs.archive.outputs.release-name }}
          body: |
            ${{ needs.archive.outputs.change-report }}
          files: |
            merit-badge-json.tar.gz
            merit-badge-markdown.tar.gz
            merit-badge-images.tar.gz
            cub-adventure-json.tar.gz
            cub-adventure-markdown.tar.gz
            scout-archive-json.tar.gz
            scout-archive-markdown.tar.gz
          draft: false
          prerelease: false

  deploy-site:
    runs-on: ubuntu-latest
    needs: archive

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.11"
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Download merit badge artifacts
        uses: actions/download-artifact@v4
        with:
          name: merit-badge-json
          path: build/merit-badges

      - name: Download merit badge markdown artifacts
        uses: actions/download-artifact@v4
        with:
          name: merit-badge-markdown
          path: build/merit-badges

      - name: Download cub adventure artifacts
        uses: actions/download-artifact@v4
        with:
          name: cub-adventure-json
          path: build/cub-scout-adventures

      - name: Download cub adventure markdown artifacts
        uses: actions/download-artifact@v4
        with:
          name: cub-adventure-markdown
          path: build/cub-scout-adventures

      - name: Build website
        run: make build-website

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site # The folder the action should deploy
          branch: gh-pages # The branch the action should deploy to
